Repository SamyakMishra072/Tic-Tac-Toe, pull requests merged in 2025-04, with the labels that each got.

#19 contrast change with hover effect
  components/Square.js
Labels: enhancement, apertre2.0, medium

#20 Update README with structured format and features
  README.md
Labels: documentation, apertre2.0, easy

#25 Fix: Add SEO meta tags #21
  pages/_app.js
Labels: apertre2.0, medium

#32 Favicon
  pages/_app.js
  public/faav.png
Labels: apertre2.0, easy

#33 Added Pull Request and Issue Templates for Better Contribution Guidelines
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation, apertre2.0, easy

#34 Added CONTRIBUTING.md Guidelines
  CONTRIBUTING.md
Labels: documentation, apertre2.0, easy

#35 Added "How to Play" Modal Instructions
  package-lock.json
  pages/index.js
Labels: documentation, apertre2.0, easy

#36 Improved Game Page Visibility & Board Layout
  components/Board.js
  components/Footer.js
  components/Square.js
  styles/globals.css
Labels: apertre2.0, medium
